- hosts: ucilnice-prototip
  become_method: sudo
  become: true
  vars:
    ansible_port: 1001
    ansible_ssh_extra_args: '-o ForwardX11=yes'
    # ansible_become_pass: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    # ansible_password: '{{ lookup("env", "ANSIBLE_PASSWORD") }}'
    installers: /mnt/ucilnice_d/install
    ansible_connection: 'ssh'
  vars_files:
    - vars/credentials.yml
    - vars/software_keys.yml
  roles:
    # - orange
    - all_classes
    # - fri_base
    # - powerdesigner
