- hosts: classroom
  become: true
  become_method: runas
  debugger: on_failed
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    logon_type: interactive
    installers: \\ucilnicesmb.fri1.uni-lj.si\ucilnice_d\install
  vars_files:
    - vars/credentials.yml
    - vars/software_keys.yml
  roles:
    # - all_classes
    # - stm32cube
    - android_studio
    #- OR-63717
    #- RA-63703
    #- VN-63728

