#- name: Install Arduino IDE
#  win_package:
#    # path: https://downloads.arduino.cc/arduino-ide/arduino-ide_2.0.0_Windows_64bit.exe
#    path: https://downloads.arduino.cc/arduino-ide/arduino-ide_2.2.1_Windows_64bit.exe
#    arguments: /S /AllUsers
#    creates_path: "%ProgramFiles%\\Arduino IDE\\Arduino IDE.exe"

# 2024: update: Full directory structure ready zip for Windows only on this URL:
# https://unilj-my.sharepoint.com/:u:/g/personal/rozman_fri1_uni-lj_si/EYTFhlsJOFtFk9xsaViP0eYBtILVS24ZF_dlkgodu_L9Nw?e=geavvJ

- name: Create STM32Duino directory
  win_file:
    path: "D:\\RAVINOR\\STM32Duino"
    state: directory

- name: Install Logisim
  win_get_url:
    url: "https://unilj-my.sharepoint.com/:u:/g/personal/rozman_fri1_uni-lj_si/EYTFhlsJOFtFk9xsaViP0eYBtILVS24ZF_dlkgodu_L9Nw?e=geavvJ"
    dest: "D:\\RAVINOR\\STM32Duino"
    # TODO Don't know if unzipping is required?


# TODO check if anything else is needed (esp8266com)?
