AndroidSDK_packages:
  - add-ons;addon-google_apis-google-24
  - add-ons;addon-google_apis-google-24
  - build-tools;34.0.0-rc3
  - build-tools;35.0.0
  - cmake;3.22.1
  #- cmake;latest
  - cmdline-tools;latest
  - emulator
  - extras;android;m2repository
  - extras;google;auto
  - extras;google;google_play_services
  - extras;google;instantapps
  - extras;google;m2repository
  - extras;google;market_apk_expansion
  - extras;google;market_licensing
  - extras;google;simulators
  - extras;google;webdriver
  # - extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2
  # - extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2
  - ndk-bundle
  # - patcher;v4
  - platform-tools
  - platforms;android-34
  - platforms;android-35
  - platforms;android-32
  - platforms;android-UpsideDownCakePrivacySandbox
  - skiaparser;3
  - sources;android-35
  - sources;android-34
  - system-images;android-35;google_apis;x86_64
  - system-images;android-34;google_apis;x86_64
  - system-images;android-32;google_apis;x86_64
  - system-images;android-35;google_apis_playstore;x86_64
  - system-images;android-34;google_apis_playstore;x86_64
  - system-images;android-UpsideDownCakePrivacySandbox;google_apis_playstore;x86_64
