- name: Install Android Studio
  block:
  - name: Create destination for Android Studio
    file:
      path: /opt/Android_Studio
      state: directory
  - name: Download and unpack Android Studio
    unarchive:
      # src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2022.3.1.19/android-studio-2022.3.1.19-linux.tar.gz
      src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2024.1.1.12/android-studio-2024.1.1.12-linux.tar.gz
      creates: /opt/Android_Studio/android-studio/build.txt
      dest: /opt/Android_Studio
      remote_src: yes

  - name: Install Android Studio Command line tools
    block:
    - name: Create destination for Android Studio Command line tools
      file:
        path: /opt/Android_SDK
        state: directory
    - name: Download and unpack Android Studio Command line tools
      unarchive:
        # src: https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2021.3.1.16/android-studio-2021.3.1.16-linux.tar.gz 
        src: https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        creates: /opt/Android_SDK/cmdline-tools/lib/README
        dest: /opt/Android_SDK
        remote_src: yes

  - name: Include Android SDK packages
    include_vars: androidsdk_packages.yml

  - name: Accept Android SDK package licenses
    shell: yes | /opt/Android_SDK/cmdline-tools/bin/sdkmanager --sdk_root=/opt/Android_SDK --licenses

  - name: Install Android SDK packages
    command: /opt/Android_SDK/cmdline-tools/bin/sdkmanager --sdk_root=/opt/Android_SDK --install "{{ item }}"
    loop: "{{ AndroidSDK_packages }}"
