- name: Enable non-privileged users to run wireshark
  ansible.builtin.debconf:
    name: wireshark
    question: wireshark-common/install-setuid
    value: true
    vtype: boolean
- name: "Install Wireshark"
  apt:
    name: wireshark
    state: latest
- name: "Install text-mode wireshark"
  apt:
    name: tshark
    state: latest
