# Vhodno-izhodne naprave
# Robert.Rozman@fri.uni-lj.si
# Windows, CubeIDE + Tools, LTSpice, PulseView, RAVINOR
dependencies:
  - role: stm32cube
  - role: stm32duino
  - role: vscode
  - role: ltspice
  - role: pulseview
  - role: putty
  - role: algobuilder

