# Vhodno-izhodne naprave
# Robert.Rozman@fri.uni-lj.si
# Windows, CubeIDE + Tools, STMDuino, VSCode, LTSpice, PulseView,Putty, STM32 Algobuilder & Unicleo GUI
dependencies:
  - role: stm32cube
  - role: stm32duino
  - role: vscode
  - role: ltspice
  - role: pulseview
  - role: putty
  - role: stm32mems-studio    # replaces algobuilder and unicleogui
#  - role: stm32algobuilder   #(ni še exe. Datoteke - ne dobim iz ST portala)
#  - role: stm32unicleogui
 
#TODO Writable d:\RAVINOR directory
