# Informacijski sistemi
# Miha.Grohar@fri.uni-lj.si
# Windows, GNU/Linux, Docker, VS Code, dotnet6 SDK, GIT, Android Studio
dependencies:
  - role: docker
  - role: vscode
  - role: dotnet
  - role: git
  - role: android_studio

