- name: Set Matlab version and destination
  set_fact:
    target_version: "R2024a_Update_5"
    license_path: \\ucilnicesmb.fri1.uni-lj.si\ucilnice_d\install\matlab\network.lic
    dest_dir: D:\matlab

- name: Mount Matlab ISO
  win_disk_image:
    image_path: "{{ installers }}\\matlab\\{{ target_version }}_Windows.iso"
    state: present
  register: disk_image

- name: Prepare installer_input.txt
  template:                                                                                
    src: installer_input.txt
    dest: d:\matlab_installer_input.txt

- name: Install Matlab
  win_package:
    path: "{{ disk_image.mount_paths[0] }}\\setup.exe"
    arguments: -inputFile "d:\\matlab_installer_input.txt"

- name: Unmount Matlab ISO
  win_disk_image:
    image_path: "{{ installers }}\\matlab\\matlab-{{ target_version }}_windows.iso"
    state: absent

# TODO MATLAB throws license error -83 when run
- name: Install Matlab license
  win_copy:
    dest: "{{ dest_dir }}\\licenses\\network.lic"
    src: "{{ installers }}\\matlab\\network.lic"
    remote_src: yes
