- name: Install Julia from tarball
  block:
  - name: Create destination for Julia
    file:
      path: /opt/Julia
      state: directory
  - name: Download and unpack Julia
    unarchive:
      src: https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.4-linux-x86_64.tar.gz
      dest: /opt/Julia
      remote_src: yes

