# # SageMath se se prevede za Ubutnu 24.04: https://github.com/sagemath/sage/issues/38051#issuecomment-2123452861
# - name: Install SageMath - Jupyter
#   apt:
#     name: sagemath-jupyter
#     state: latest

- name: Do not install SageMath
  debug:
    msg: SageMath is not installable on Ubuntu 24.04 right now
