# Organizacija računalnikov
# Robert.Rozman@fri.uni-lj.si
# Windows, Logisim, Logisim Evolution, RAVINOR, CubeIDE + QEMU Embedded plugin
dependencies:
  - role: logisim
  - role: stm32cube
  - role: stm32duino
  - role: putty
  - role: ninja
  - role: cmake
  - role: gcc-arm
# TODO: RAVINOR, CubeIDE
