- name: Install TwinCat 3
  debug:
    msg: TODO - write twincat installer scripts
  #win_package:
  #  path: "{{ installers }}\\TwinCat3\\setup\\setup.exe"
  #  arguments: "/s /f1\"{{ installers }}\\PowerDesigner 12.5\\setup.iss\" /f2\"C:\\powerdesigner_log.iss\""
