# TODO check install status
- name: Check AlgoBuilder install status
  win_stat:
    path: C:\Program Files (x86)\Thonny\thonny.exe
  register: file

- when: not file.stat.exists
  block:
    - name: Download AlgoBuilder
      win_command: wget "https://unilj-my.sharepoint.com/:u:/g/personal/rozman_fri1_uni-lj_si/EZhqHxJoAfdEjdlMu0uGWGcBOqrT0vTVv2_nhynWZ3fOwQ?e=rcskhq&download=1" -O C:\AlgoBuilderSuite.exe
      args:  
        creates: C:\AlgoBuilderSuite.exe
      #win_get_url:
      #  follow_redirects: all
      #  http_agent: Wget/1.21.3
      # url: https://unilj-my.sharepoint.com/:u:/r/personal/rozman_fri1_uni-lj_si/Documents/Arhiv/ImportantFiles/AlgoBuilderSuite.exe?download=1
      #  dest: C:\AlgoBuilderSuite.exe
      #register: download
    
    - name: Install AlgoBuilder
      win_package:
        path: C:\AlgoBuilderSuite.exe
        # path: "{{ download.dest }}"
        arguments: /Verysilent /AllUsers
    
    - name: Remove temporary files
      win_file:
        path: C:\AlgoBuilderSuite.exe
        # path: "{{ download.dest }}"
        state: absent
