- name: Install Oracle JDK
  win_package:
    path: https://download.oracle.com/java/22/latest/jdk-22_windows-x64_bin.msi
    arguments: INSTALLLEVEL=3

- name: Find Java version
  win_reg_stat:
    path: HKLM:\SOFTWARE\JavaSoft\JDK
    name: CurrentVersion
  register: reg

- name: Find Java home
  win_reg_stat:
    path: "HKLM:\\SOFTWARE\\JavaSoft\\JDK\\{{ reg['value'] }}"
    name: JavaHome
  register: reg

- name: Set JAVA_HOME
  win_environment:
    name: JAVA_HOME
    value: "{{ reg['raw_value'] }}"
    level: machine

- name: Add "." to CLASSPATH
  win_path:
    name: CLASSPATH
    elements: "."
    state: present
    scope: machine

- name: Disable Java updates
  win_regedit:
    path: HKLM:\SOFTWARE\WOW6432Node\JavaSoft\Java Update\Policy
    name: EnableJavaUpdate
    type: dword
    data: 0

#- name: Download Java documentation
# TODO: download Java doc
- name: Download Java doc
  win_get_url:
    path: "{{ reg['raw_value'] }}"
    url: https://download.oracle.com/otn_software/java/jdk/22.0.2+9/c9ecb94cd31b495da20a27d4581645e8/jdk-22.0.2_doc-all.zip
    register: downloaded_docs

- name: Unpack Java docs
  win_unzip:
    path: "{{ downloaded_docs }}"
    dest: "{{ reg['raw_value'] }}\\docs"
    delete_archive: yes
