- name: Install OpenJDK 21
  apt:
    name: openjdk-21-jdk
    state: latest

- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: latest

- name: Install OpenJDK 11
  apt:
    name: openjdk-11-jdk
    state: latest

- name: Install default JDK
  apt:
    name: default-jdk
    state: latest

- name: Install Java docs
  apt:
    name: default-jdk-doc
    state: latest


- name: Install Oracle Java dependencies
  apt:
    name: 
      - libc6-i386
      - libc6-x32
    state: latest

- name: Install Oracle JDK 22
  apt: 
    deb: "https://download.oracle.com/java/22/latest/jdk-22_linux-x64_bin.deb"

- name: Install Java docs
  apt: 
    deb: "https://download.oracle.com/java/22/latest/jdk-22_linux-x64_bin.deb"

