# TODO install logisim for linux
- name: Install Logisim
  block:
  - name: Create destination for Logisim
    file:
      path: /opt/logisim
      state: directory
  - name: Download and unpack Logisim
    unarchive:
      src: https://deac-fra.dl.sourceforge.net/project/circuit/2.7.x/2.7.1/logisim-generic-2.7.1.jar
      dest: /opt/logisim
      remote_src: yes
      creates: /opt/logisim/META-INF/MANIFEST.MF
  - name: Download and unpack Logisim - Evolution
    unarchive:
      src: https://github.com/logisim-evolution/logisim-evolution/releases/download/v3.9.0/logisim-evolution-3.9.0-all.jar
      dest: /opt/logisim-evolution
      remote_src: yes
      creates: /opt/logisim-evolution/META-INF/MANIFEST.MF
